# Generated by Django 5.0.6 on 2024-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_alter_historicalperformance_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='purchase_orders',
            field=models.ManyToManyField(related_name='vendors', to='vendor_app.purchaseorder'),
        ),
    ]
